### PR TITLE
Ensure code matches new repository name

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR updates all references now that this repo has been renamed from `ansible-role-assessor-portal` to `ansible-role-assessor-workbench`.

## 💭 Motivation and context ##

We want to ensure that the code is up-to-date with regard to the repository name, otherwise confusion reigns supreme.

## 🧪 Testing ##

All automated tests pass.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔ Just to verify: Did you tear down the old Terraform configuration?

**Comment by dav3r** [comment]
> LGTM ✔ Just to verify: Did you tear down the old Terraform configuration?

I didn't remember to do a `terraform destroy` on the old config before I deleted my local copy of the directory, but I did manually delete the resources involved (users, roles, policies), so we should be ok.

**Review by felddy — APPROVED** [review]
what-is-happening-tst3k-poltergeist
Thank you for doing this.

**Comment by dav3r** [comment]
> > LGTM ✔ Just to verify: Did you tear down the old Terraform configuration?
> 
> I didn't remember to do a `terraform destroy` on the old config before I deleted my local copy of the directory, but I did manually delete the resources involved (users, roles, policies), so we should be ok.

I forgot that I could still run a `terraform destroy` if I switched back to the current develop branch (prior to merging this PR), so I went ahead and did that, which confirmed that my manual cleanup effort was successful.

**Pull request merged**
